    python Matrix 矩陣 用法

In [1]:
import numpy as np

In [2]:
A = np.array([
    [1+1, 1+2, 1+3, 1+4],
    [2+1, 2+2, 2+3, 2+4],
    [3+1, 3+2, 3+3, 3+4]
])

In [3]:
A

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [12]:
A[0]

array([2, 3, 4, 5])

In [13]:
A[1][1]

4

In [4]:
B=np.array([
    [1,2,3,4],
    [2,3,4,5],
    [3,4,5,6]
])

In [5]:
A+B

array([[ 3,  5,  7,  9],
       [ 5,  7,  9, 11],
       [ 7,  9, 11, 13]])

    直接成的話 會變成相同位置得值 相成

In [6]:
A*B

array([[ 2,  6, 12, 20],
       [ 6, 12, 20, 30],
       [12, 20, 30, 42]])

    要用dot的方法才符合 矩陣的運算規則

In [8]:
C = np.array([
    [4, -3, 2],
    [0, 1, -1],
    [5, 4, 0]
])
D = np.array([
    [2, 2, -5],
    [3, 1, 0],
    [-1, 1, 4]
])
print(C.dot(D))

[[ -3   7 -12]
 [  4   0  -4]
 [ 22  14 -25]]


    單位矩陣

In [9]:
np.eye(2, dtype = 'int')

array([[1, 0],
       [0, 1]])

In [10]:
np.eye(3, dtype = 'int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [11]:
np.eye(5, dtype = 'int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

    轉換矩陣

In [14]:
M=np.array([
    [1,2],
    [3,4]
])

In [15]:
M.T

array([[1, 3],
       [2, 4]])

    反矩陣

In [16]:
M=np.array([
    [1,2],
    [3,4]
])

In [19]:
np.linalg.inv(M)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

    ref:https://medium.com/pyradise/%E4%BD%BF%E7%94%A8-python-%E4%BE%86%E8%AA%8D%E8%AD%98%E7%9F%A9%E9%99%A3-915376207187